### PR TITLE
Allow Wayland sessions to start on seat0 on kernels with no VTs

### LINKED ISSUE #314: lightdm doesn't start Wayland sessions on seat0's without VTs
Hi

This is LightDM v1.30 (not 1.32 I will admit)

Testing using lightdm on a kernel compiled with CONFIG_VT=n and trying to start a Wayland session and trying to start a Wayland enabled KDE session, takes me back to the login screen

In the journal, I am seeing a number of lines like `Jul 22 13:22:12 test-Standard-PC-Q35-ICH9-2009 lightdm[587]: Error opening /dev/tty0: No such file or directory` and 
`Jul 22 13:22:20 test-Standard-PC-Q35-ICH9-2009 lightdm[915]: pam_systemd(lightdm:session): Failed to create session: Seat has no VTs but VT number not 0`

Looking at `get_vt` `src/seat-local.c` that check might need to be changed from checking if the seat is `seat0` by string, to instead use CanTTY https://www.freedesktop.org/software/systemd/man/org.freedesktop.login1.html#CanTTY

as while only seat0 has VTs, not all seat0's have VTs

Thanks

### PR DESCRIPTION
**Pull request by n3rdopolis**
This is an attempt to fix #314

### CODE REVIEW

**Comment by n3rdopolis** [comment]
Wait It looks like it wants my dang address to be able to merge?

**Comment by n3rdopolis** [comment]
It's only a few lines, so you do have my permission to use it, but I don't want to fill out my address and whatnot

**Comment by qwertychouskie** [comment]
I never even noticed the CLA had an address and phone field, probably because I just instinctively put something random like every other webform.  Unless you like plan on signing an employment agreement with Canonical in the future or something, name/username and country is functionally just fine.

I'd like to see these fields removed, but there's probably some weird lawyery reason they can't officially remove the fields.

(I'd still take Canonical's CLA approach to things any day over Red Hats' [bleep]-the-GPL-you-are-not-rich-enough-to-sue-us-anyways approach.)

**Comment by n3rdopolis** [comment]
> I never even noticed the CLA had an address and phone field, probably because I just instinctively put something random like every other webform. Unless you like plan on signing an employment agreement with Canonical in the future or something, name/username and country is functionally just fine.
> 
> I'd like to see these fields removed, but there's probably some weird lawyery reason they can't officially remove the fields.
> 
> (I'd still take Canonical's CLA approach to things any day over Red Hats' [bleep]-the-GPL-you-are-not-rich-enough-to-sue-us-anyways approach.)

OK, It also seems to want a "Please add the Canonical Project Manager or contact" which I have no idea what to fill in for that? Maybe `lightdm`?

**Comment by JezerM** [comment]
> OK, It also seems to want a "Please add the Canonical Project Manager or contact" which I have no idea what to fill in for that? Maybe `lightdm`?

Yeah, that's a weird field. I just added "Robert Ancell" as he's the main contributor of this project.

**Comment by n3rdopolis** [comment]
Odd that it's failing now. I wonder if I was supposed to add the ~ in the launchpad ID or not...

**Comment by JezerM** [comment]
You must push a new commit, or force push, to trigger the GitHub Action.

**Comment by n3rdopolis** [comment]
Well lets see, I did realize that I accidentally added an extra space that isn't needed, so I will remove it, repush, and see how that goes

**Comment by qwertychouskie** [comment]
`n3rdopolis ✕ (issue checking CLA status [HttpError: User does not exist or is not a member of the organization])`

Strange.  Maybe @robert-ancell has some insight into the error?

**Comment by JezerM** [comment]
It failed xD

Make sure your Launchpad email is the same you have in GitHub. Even if the ID is the same as GitHub's, it seems it checks your email instead.

**Comment by n3rdopolis** [comment]
I wonder if some file has to replicate inside some server after signing it, before it is visible to Github

**Comment by FunkyFinch** [comment]
Are there any updates on this PR? Did you have success with your changes?

**Comment by n3rdopolis** [comment]
Not much success, I am not sure where to put the dbus call...

**Comment by n3rdopolis** [comment]
Sorry about the last comment, I thought this was sddm for a moment. This PR works for me

**Comment by n3rdopolis** [comment]
Any chance of this being reviewed?

**Comment by n3rdopolis** [comment]
I would like to request a review on this if possible

**Comment by n3rdopolis** [comment]
@robert-ancell is it possible to review this please?

**Comment by n3rdopolis** [comment]
Are there changes that need to be made here?

**Review by robert-ancell — APPROVED** [review]
Thanks!

**Pull request merged**
