### PR TITLE
Fix typos found with codespell

### PR DESCRIPTION
**Pull request by ggvl**

### CODE REVIEW

**Comment by robert-ancell** [comment]
@ggvl are you able to sign the CLA? Thanks!

**Comment by ggvl** [comment]
Signed on https://ubuntu.com/legal/contributors

**Comment by ggvl** [comment]
> @ggvl are you able to sign the CLA? Thanks!

Signed on https://ubuntu.com/legal/contributors

**Comment by ggvl** [comment]
@robert-ancell CLA check pass.

**Pull request merged**
